# Generated by Django 5.0.1 on 2024-01-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
